### ISSUE TITLE
补充文档中 settings.yml 中的 Cheat-Client-Secure-Chat: true

### ISSUE THREAD

**Issue by postyizhan** [ItsFlicker/document-trchat#1]
加载Trchat时发现

![图片](https://github.com/ItsFlicker/document-trchat/assets/97342038/d98ac4b2-b51e-457b-9c3a-6349c1ca97ac)

查阅文档 https://trchat.trixey.cc/guide/configuration 中的settings.yml

没有找到  `Cheat-Client-Secure-Chat: true`

拆开TrChat的jar找到 settings.yml 中有 `Cheat-Client-Secure-Chat: true`

请补全文档

**Comment by ItsFlicker** [comment]
已补全
